lib/eg_web/router.ex
defmodule EgWeb.Router do
  use EgWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EgWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EgWeb do
    pipe_through :browser # Use the default browser stack

    # get "/", PageController, :index
    resources "/", JobsController

    # jobs_path  GET     /                         EgWeb.JobsController :index
    # jobs_path  GET     /:id/edit                 EgWeb.JobsController :edit
    # jobs_path  GET     /new                      EgWeb.JobsController :new
    # jobs_path  GET     /:id                      EgWeb.JobsController :show
    # jobs_path  POST    /                         EgWeb.JobsController :create
    # jobs_path  PATCH   /:id                      EgWeb.JobsController :update
    #            PUT     /:id                      EgWeb.JobsController :update
    # jobs_path  DELETE  /:id                      EgWeb.JobsController :delete
  end

  scope "/auth", EgWeb do
    pipe_through :browser

    get "/signout", AuthController, :signout
    # request is defined by Ueberauth
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

end

lib/eg/application.ex
defmodule Eg.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Eg.Repo, []),
      # Start the endpoint when the application starts
      supervisor(EgWeb.Endpoint, []),
      # Start your own worker by calling: Eg.Worker.start_link(arg1, arg2, arg3)
      # worker(Eg.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Eg.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    EgWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/eg/job.ex
defmodule Eg.Job do
  use Ecto.Schema
  import Ecto.Changeset
  alias Eg.Job

  schema "jobs" do
    field :apply, :string
    field :company, :string
    field :description, :string
    field :email, :string
    field :location, :string
    field :rate, :integer
    field :title, :string
    field :twitter, :string
    field :type, :string
    field :url, :string
    belongs_to :user, Eg.User

    timestamps()
  end

  @doc false
  def changeset(%Job{} = job, attrs) do
    job
    |> cast(attrs, [:title, :type, :rate, :location, :description, :company, :url, :twitter, :email, :apply])
    |> validate_required([:title])
  end
end

lib/eg/repo.ex
defmodule Eg.Repo do
  use Ecto.Repo, otp_app: :eg

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/eg/user.ex
defmodule Eg.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Eg.User

  schema "users" do
    # field :id, :integer
    field :email, :string
    field :provider, :string
    field :token, :string
    has_many :jobs, Eg.Job

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :provider, :token])
    |> validate_required([:email, :provider, :token])
  end

end

lib/eg_web/controllers/auth_controller.ex
defmodule EgWeb.AuthController do
  use EgWeb, :controller
  plug Ueberauth

  alias Eg.User
  alias Eg.Repo

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, params) do
    user_params = %{token: auth.credentials.token, email: auth.info.email, provider: Atom.to_string(auth.provider)}
    changeset = User.changeset(%User{}, user_params)

    signin(conn, changeset)
  end

  def signin(conn, changeset) do
    case insert_or_update_user(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> put_session(:user_id, user.id)
        |> redirect(to: jobs_path(conn, :index))
      {:error, _reason} ->
        conn
        |> put_flash(:error, "Error signing in")
        |> redirect(to: jobs_path(conn, :index))
    end
  end

  def signout(conn, _params) do
    conn
    |> configure_session(drop: true)
    |> redirect(to: jobs_path(conn, :index))
  end

  defp insert_or_update_user(changeset) do
    case Repo.get_by(User, email: changeset.changes.email) do
      nil ->
        Repo.insert(changeset)
      user ->
        {:ok, user}
    end
  end

end

lib/eg_web/controllers/jobs_controller.ex
defmodule EgWeb.JobsController do
  use EgWeb, :controller

  alias Eg.Job
  alias Eg.Repo

  plug EgWeb.Plugs.RequireAuth when action in [:new, :create, :edit, :update, :delete]
  plug :check_job_owner when action in [:update, :edit, :delete]

  def index(conn, _params) do
    jobs = Repo.all(Job)
    render conn, "index.html", jobs: jobs
  end

  def show(conn, %{"id" => job_id}) do
    job = Repo.get(Job, job_id)
    render conn, "show.html", job: job
  end

  def new(conn, _params) do
    changeset = Job.changeset(%Job{}, %{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"job" => job}) do
    changeset = conn.assigns.user
      |> Ecto.build_assoc(:jobs)
      |> Job.changeset(job)

    case Repo.insert(changeset) do
      {:ok, _job} ->
        conn
        |> put_flash(:info, "Job Created")
        |> redirect(to: jobs_path(conn, :index))
      {:error, changeset} ->
        render conn, "new.html", changeset: changeset
    end
  end

  def edit(conn, %{"id" => job_id}) do
    job = Repo.get(Job, job_id)
    changeset = Job.changeset(job, %{})
    render conn, "edit.html", changeset: changeset, job: job
  end

  def update(conn, %{"id" => job_id, "job" => updated_job}) do
    old_job = Repo.get(Job, job_id)
    changeset = Job.changeset(old_job, updated_job)

    case Repo.update(changeset) do
      {:ok, _job} ->
        conn
        |> put_flash(:info, "Job Updated")
        |> redirect(to: jobs_path(conn, :index))
      {:error, changeset} ->
        render conn, "edit.html", changeset: changeset, job: old_job
    end
  end

  def delete(conn, %{"id" => job_id}) do
    Repo.get!(Job, job_id) |> Repo.delete!

    conn
    |> put_flash(:info, "Job Deleted")
    |> redirect(to: jobs_path(conn, :index))
  end

  def check_job_owner(conn, _params) do
    %{params: %{"id" => job_id}} = conn

    if Repo.get(Job, job_id).user_id == conn.assigns.user.id do
      conn
    else
      conn
      |> put_flash(:error, "You cannot edit that")
      |> redirect(to: jobs_path(conn, :index))
      |> halt()
    end
  end
end

lib/eg_web/controllers/page_controller.ex
defmodule EgWeb.PageController do
  use EgWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/eg_web/views/error_view.ex
defmodule EgWeb.ErrorView do
  use EgWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/eg_web/views/jobs_view.ex
defmodule EgWeb.JobsView do
  use EgWeb, :view
end

lib/eg_web/views/layout_view.ex
defmodule EgWeb.LayoutView do
  use EgWeb, :view
end

lib/eg_web/views/page_view.ex
defmodule EgWeb.PageView do
  use EgWeb, :view
end

lib/eg_web/templates/jobs/edit.html.eex
<%= form_for @changeset, jobs_path(@conn, :update, @job), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= text_input f, :type, placeholder: "Job type", class: "form-control" %>
    <%= text_input f, :rate, placeholder: "Day rate", class: "form-control" %>
    <%= text_input f, :location, placeholder: "Location", class: "form-control" %>
    <%= text_input f, :description, placeholder: "Description", class: "form-control" %>
    <%= text_input f, :company, placeholder: "Company name", class: "form-control" %>
    <%= text_input f, :url, placeholder: "Company url", class: "form-control" %>
    <%= text_input f, :twitter, placeholder: "Company Twitter", class: "form-control" %>
    <%= text_input f, :email, placeholder: "Company email", class: "form-control" %>
    <%= text_input f, :apply, placeholder: "How to apply", class: "form-control" %>
    <%= error_tag f, :title %>
  </div>
  <%= submit "Save Job", class: "btn btn-primary" %>
<% end %>

lib/eg_web/templates/jobs/index.html.eex
<ul class="collection">
  <%= for job <- @jobs do %>
    <li class="collection-item">
      <div class="section-flex">
        <div>
          <%= link job.title, to: jobs_path(@conn, :show, job) %>
          <p><%= job.company %></p>
        </div>
        <div class="">
          <%= link "Edit", to: jobs_path(@conn, :edit, job) %>
          <%= link "Delete", to: jobs_path(@conn, :delete, job), method: :delete %>
        </div>
      </div>
      <p><%= job.description %></p>
      <div class="section-flex">
        <p><%= job.location %></p>
        <p>£<%= job.rate %>/day</p>
      </div>
    </li>
  <% end %>
</ul>

<div class="fixed-action-btn">
  <%= link to: jobs_path(@conn, :new), class: "btn-floating btn-large red" do %>
    <i class="material-icons">add</i>
  <% end %>
  <div id="hello-react"></div>
</div>

lib/eg_web/templates/jobs/new.html.eex
<%= form_for @changeset, jobs_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= text_input f, :type, placeholder: "Job type", class: "form-control" %>
    <%= text_input f, :rate, placeholder: "Day rate", class: "form-control" %>
    <%= text_input f, :location, placeholder: "Location", class: "form-control" %>
    <%= text_input f, :description, placeholder: "Description", class: "form-control" %>
    <%= text_input f, :company, placeholder: "Company name", class: "form-control" %>
    <%= text_input f, :url, placeholder: "Company url", class: "form-control" %>
    <%= text_input f, :twitter, placeholder: "Company Twitter", class: "form-control" %>
    <%= text_input f, :email, placeholder: "Company email", class: "form-control" %>
    <%= text_input f, :apply, placeholder: "How to apply", class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <%= submit "Save Job", class: "btn btn-primary" %>
<% end %>

lib/eg_web/templates/jobs/show.html.eex
<div class="jumbotron">
  <h4><%= @job.title %> / <%= @job.type %></h4>
  <div class="section-flex">
  <%= if @job.rate do %>
    <p>£<%= @job.rate %>/day</p>
  <% end %>
  <p><%= @job.location %></p>
  </div>
  <p>Company: <%= @job.company %></p>
  <p><%= @job.description %></p>
  <p>Email: <%= @job.email %></p>
  <p>Website: <%= @job.url %></p>
  <p>Twitter: <%= @job.twitter %></p>
  <p><%= @job.apply %></p>
</div>

lib/eg_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Eg!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script>
      <%= if @conn.assigns.user do %>
        window.userToken = "<%= Phoenix.Token.sign(EgWeb.Endpoint, "key", @conn.assigns.user.id) %>"
      <% end %>
    </script>
  </head>

  <body>
    <nav class="light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          Cannes Lions
        </a>
        <ul class="right">
          <%= if @conn.assigns[:user] do %>
            <li>
              <%= link "Sign Out", to: auth_path(@conn, :signout) %>
            </li>
          <% else %>
            <li>
              <%= link "Sign in with Github", to: auth_path(@conn, :request, "github") %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/eg_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>